services:
  phase-hw:
    build:
      context: .
    container_name: phase-hw
    ports:
      - "127.0.0.1:5000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./src/:/app/src/
